### ISSUE TITLE
Response of Discovery service is not optimized

### ISSUE THREAD

**Issue by AlaGarali** [watson-developer-cloud/conversation-enhanced#127] opened 2018-07-12 15:41 UTC
I'm trying to build Customer Support Agent with Watson Conversation and Discovery Service and uploading FAQs documents (.docx, .pdf, .html) to Discovery service.

I would like to know, how can I have the right answer of a question asked, from documents (html, docx, pdf, ...) uploaded on discovery service ? How can I configure discovery service or discovery.query (){} to return the best answer of user's question ? Should I use another service such as WKS or not ? Please find below my discovery.js file code:

```js
 function sendToDiscovery(query) {
  return new Promise(function(resolve, reject) {
    var DiscoveryV1 = require('watson-developer-cloud/discovery/v1');

    var discovery = new DiscoveryV1({
      username: process.env.DISCOVERY_USERNAME,
      password: process.env.DISCOVERY_PASSWORD,
      version_date: '2018-03-05'
    });

    var environment_id = process.env.ENVIRONMENT_ID;
    var collection_id = process.env.COLLECTION_ID;
    var params = {query: query,
        //natural_language_query: query
        //filter: score>0.8,
        highlight: true,
        passages_count: 1,
        passages: true,
        return_fields: ['text'],
        count:1,
        return: 'text'
        //aggregation:
        //'[term(enriched_text.entities.text).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.categories.label).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.concepts.text).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.keywords.text).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.entities.type).term(enriched_text.sentiment.document.label)]'
    }
    discovery.query({
      environment_id: environment_id,
      collection_id: collection_id,
      configuration_id: process.env.DISCOVERY_CONFIGURATION_ID,
      query : params
    }, function(error, response) {
        if (error) {
          reject(error);
        } else {
          if (response.results == null) {
            console.log("The call to the Discovery service is complete, but he has not returned any replies. Check the format of the data injected into the Discovery service.");
            reject(error);
          } else {
            console.log(response.results[0].text);
            resolve(response.results[0].text);
          }
        }
    });
  });
}
module.exports = sendToDiscovery;
```

Could you help me please ?

Best regards.

**Comment by Oliver-I** [comment] 2018-07-16 04:35
@stevenpkg Can you take a look at this?

**Comment by stevenpkg** [comment] 2018-07-16 04:48
@AlaGarali your best ask developer questions at https://stackoverflow.com/questions/tagged/watson-discovery

**Comment by germanattanasio** [comment] 2018-07-17 02:24
This is a duplicate of https://github.com/watson-developer-cloud/assistant-with-discovery-openwhisk/issues/51

**Closed as completed by germanattanasio** 2018-07-17 02:24 UTC
Labels: question
